---
- hosts: all
  tasks:

    - name: Install Zabbix Repository Key
      rpm_key: state=present key=http://repo.zabbix.com/RPM-GPG-KEY-ZABBIX 
      become: true

    - name: Install Zabbix Repository and other packages needed by Ansible
      yum: pkg={{item}} state=installed  
      with_items:
        - https://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/zabbix-release-3.4-2.el7.noarch.rpm
      become: true 

    - name: Remove zabbix agent for RedHat OS family
      yum: pkg={{item}} state=absent
      with_items:
          - zabbix-agent
      become: true

    - name: Install zabbix agent for RedHat OS family
      yum: pkg={{item}} state=installed
      with_items:
          - zabbix-agent
      become: true

    - name: Configure zabbix agent
      template: 
        src: templates/zabbix_agentd.conf.j2 
        dest: /etc/zabbix/zabbix_agentd.conf
        mode: 0644
      become: true

    - name: Create zabbix agent optional config directory
      file: path=/etc/zabbix/zabbix_agentd.d/customs state=directory
      become: true

    - name: ensure zabbix agent started/stopped
      service: 
        name: zabbix-agent 
        state: started
      become: true
